statefulSet:
  metadata:
    name: postgres
  spec:
    serviceName: postgres
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        initContainers:
          - name: volume-permissions
            image: busybox
            imagePullPolicy: "IfNotPresent"
            command: 
              - sh 
              - -c 
              - "mkdir -p /mnt/data && chown -R 999:999 /mnt/data"
            volumeMounts:
              - mountPath: /mnt/data 
                name: postgredb
        containers:
          - name: postgres
            image: postgres:17.4 
            imagePullPolicy: "IfNotPresent"
            ports:
              - containerPort: 5432  
            envFrom:
              - configMapRef:
                  name: postgres-envs
              - secretRef:
                  name: postgres-secret
            env:
              - name: PGDATA
                value: /mnt/data/pgdata
            volumeMounts:
              - mountPath:  /mnt/data
                name: postgredb
        volumes:
          - name: postgredb
            persistentVolumeClaim:
              claimName: postgres-volume-claim

