apiVersion: v2
name: app-stack
description: A Helm chart for deploying a Razor Page application with PostgreSQL
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgres
    version: "0.1.0"
    repository: "file://charts/postgres"
  - name: application
    version: "0.1.0"
    repository: "file://charts/application"
    condition: application.enabled