apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-envs
  namespace: dotnet-application
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword123