apiVersion: v1
kind: Service
metadata:
  namespace: dotnet-application
  name: postgres-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres

# kubectl apply -f postgres.service.yml -n dotnet-application
# kubectl exec -it postgres-0 -n dotnet-application -- /bin/bash