apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  namespace: dotnet-application
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: ""
  volumeName: postgres-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi