---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dotnet-application
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /mnt/data"]
          volumeMounts:
            - mountPath: /mnt/data #/var/lib/postgresql/data
              name: postgredb
      containers:
        - name: postgres
          image: postgres:17.4 
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-envs 
          # env:
          #   - name: POSTGRES_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: postgres-secret
          #         key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath:  /mnt/data # /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-volume-claim

# kubectl apply -f postgres.statefulset.yml -n dotnet-application
# kubectl get statefulset -n dotnet-application
# kubectl delete statefulset postgres -n dotnet-application
# kubectl describe statefulset postgres -n dotnet-application
# kubectl exec -it postgres-0 -n dotnet-application -- bash
# psql -U postgres
# \l   -- List databases
# \c ps_db
# \dt


