
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dotnet-application
  name: postgres
spec:
  serviceName: postgres
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-envs
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
  volumeClaimTemplates:  # It doesn't need a pvc. It is definition of a dynamic pvc.
    - metadata:
        name: postgres-storage
      spec:
        storageClassName: managed-csi   # <-- Or your preferred StorageClass
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi