apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: pg-disk
    diskURI: "/subscriptions/34e29c3a-38a3-4f12-a3b9-990eca0cbcbf/resourceGroups/CertificateIssuer101/providers/Microsoft.Compute/disks/aks101cluster-disk"

