apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dotnet-application
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: ""
  volumeName: postgres-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


# kubectl apply -f postgres.pvc.yml -n dotnet-application
# kubectl get pvc -n dotnet-application
# kubectl delete pvc postgres-volume-claim -n dotnet-application