apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.metadata.name }}
  labels: {{.Values.service.metadata.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.spec.type }}
  ports:
  {{- range .Values.service.spec.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector: {{ .Values.service.spec.selector | toYaml | nindent 4 }}
