apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.metadata.name }}
  namespace: {{ .Values.deployment.metadata.namespace }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  selector: 
    matchLabels:
      app: {{ .Values.deployment.spec.selector.matchLabels.app }}
  strategy:
    type: {{ .Values.deployment.spec.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.spec.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.spec.strategy.rollingUpdate.maxUnavailable }}
  minReadySeconds:  {{ .Values.deployment.spec.minReadySeconds }}
  template:
    metadata:
      labels:
        app:  {{ .Values.deployment.spec.template.metadata.labels.app }}
    spec:  
      nodeSelector:
        "kubernetes.io/os": {{ .Values.deployment.spec.template.spec.nodeSelector.os }}
      serviceAccountName: {{ .Values.deployment.spec.template.spec.serviceAccountName }}
      containers:
      {{- range .Values.deployment.spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
          {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
          {{- end }}
      {{- end }}