apiVersion: v1
kind: Service
metadata:
  name: razor-app-service
  namespace: dotnet-application
  labels: {}
spec:
  type: LoadBalancer #ClusterIP #LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector: 
    app: razor-app