apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: "" #managed-csi
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: pg-disk
    diskURI: "/subscriptions/b822363d-6075-4596-987a-1f24bce600dd/resourceGroups/CertificateIssuer101/providers/Microsoft.Compute/disks/pg-disk"

  # hostPath:
  #   path: /data/postgresql

  # kubectl apply -f postgres.pv.yml 
  # kubectl get pv
  # kubectl delete pv postgres-volume -n dotnet-application

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    type: {{ .Values.persistentVolume.labels.type }}
    app: {{ .Values.persistentVolume.labels.postgres }}
spec:
  storageClassName: {{.values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes: {{ .Values.persistentVolume.accessModes }}
  azureDisk:
    kind: {{ .Values.persistentVolume.azureDisk.kind }}
    diskName: {{ .Values.persistentVolume.azureDisk.diskName }}
    diskURI: {{ .Values.persistentVolume.azureDisk.diskURI }}