---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-envs
  namespace: dotnet-application
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: postgres #ps_user
  POSTGRES_PASSWORD: postgres #SecurePassword123
  

# kubectl apply -f postgres.configMap.yml -n dotnet-application
# kubectl get configmap -n dotnet-application
# kubectl delete configmap postgres-secret -n dotnet-application
# kubectl get configmap postgres-envs -n dotnet-application -o yaml