apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
  namespace: dotnet-application
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: app.example.com
  dnsNames:
    - app.example.com
